sPHENIX-Collaboration/utilities

utils/rebuild/packages.txt
This will add the g4vertex module so approval can be merged with the pull request on core software.
=> add g4vertex to build order

utils/rebuild/packages.txt
This adds the pmonitor project to the nightly rebuild. Note that we first need to satisfy my corresponding pull request in coresoftware so the area is there to begin with.
=> mlp - added the pmonitor to the nightly rebuild

utils/rebuild/build.pl
produces now a consistent build by pulling in correct root dependent libs
=> use root version when dealing with genfit (which is special case)

utils/rebuild/packages.txt
Relocate the location for the hepmc lib for the new HepMC input work flow. Works with https://github.com/sPHENIX-Collaboration/coresoftware/pull/364
=> Pileup simulation and new HepMC input work flow

utils/rebuild/build.pl
with the demise of rcf2 the old tinderbox stopped to work. After figuring out how this machinery which has been working unchanged for the last 20 years actually does its job it's back. The output goes now to a separate sPHENIX web page and does not mix with PHENIX anymore.
=> revive tinderbox, put sPHENIX tinderbox output on its own web page

utils/rebuild/build.pl
We have a test server with the new coverity version. That requires the use of another user in the coverity commit command
=> change coverity user for coverity version 8 test

utils/rebuild/build.pl
We have a test server with the new coverity version. That requires the use of another user in the coverity commit command
=> oops coverity host name has also changed

utils/rebuild/build.pl
the third party packages to be copied are hardcoded right now, the current root6 play build needs the same packages
=> no copying of special packages for play build

utils/rebuild/build.pl
this change should take care of the warnings from libtool that it needs to relink libraries. More changes are needed but this will keep us going
=> replace /afs/.rhic.bnl.gov by /afs/rhic.bnl.gov in *.la files

utils/rebuild/build.pl
no more guessing what was run for each build. Also replace sl7 option by lafiles which is more appropriate since it just keeps the lafiles
=> print out commands which are run to configure and compile

utils/rebuild/build.pl
I think we shot ourselves in the foot by limiting the load for distcc/ccache builds. An ongoing local build (coverity, insure) could drive the load above 8 and then distcc/ccache builds ran only with 1 thread. Now also localhost is out of the distcc config (.distcc/hosts under the phnxbld account) so these builds will not load the phnxbld machine
=> use -l for local builds (insure, coverity) to limit load, unlimited for distcc/ccache

utils/rebuild/build.pl
small bugfix: in case there is a non zero sized insure reports, the parsing went into a closed logfile
=> close logfile after insure reports are analyzed

utils/rebuild/build.pl
Finally get rid of empty html files. The new coverity version (8.7.1) seems to instrument the code with coverity_ignore before analyzing which suppresses invalid_iterator errors. I guess this is their mechanism to remove false positives (I hope, these are not in our code). But this cannot be parsed from the output of the cov-analyze command which we use to trigger the creation of the html file, only the output of cov-format-errors which generates them gives a hint how many errors there were. Now the output of cov-format-errors is used to determine if the html output should be added to the coverity web output. Now all packages listed on the coverity web page actually do have errors
=> Fix coverityhtml

utils/rebuild/build.pl
git ls-remote writes a from <repository> to stderr which triggered a mail by the build script. The stderr output is now redirected to /dev/null, also replaced Phenix/PHENIX by sPHENIX in the mails which are send
=> suppress writing to stderr resulting in mail by cronjob

utils/rebuild/packages.txt
Change to the build order required by the tracking simulations reorganization (PR#529). Tested and debugged using a private build.
=> Modified build order to accomodate tracking simulations reorganization

utils/rebuild/build.pl, utils/rebuild/packages.txt
Under root6.14.00 (our afs version) rootcling cannot find g4celldefs which is not installed at that time, trackbase needs to be build after g4detectors. run make install-data with multiple jobs - under root6 it triggers rootcling to create the pcm files which takes a long time single threaded
=> Fix packageorder

utils/rebuild/build.pl
The installation of the pcm files for root6 is now done by the Makefiles. No more need to copy them after the build. With that the root6 option for the build script is obsolete
=> remove obsolete root6 option

utils/rebuild/build.pl, utils/rebuild/packages.txt
the prototype reco code (including history) was moved to the prototype repo. The owner of the repo is now an option so builds of private forks can be done without editing the script
=> move prototype reco to prototype repo

utils/rebuild/build.pl
This PR is for user builds using --repoowner='string'. While we are more or less guaranteed that all repos exist under the sPHENIX-Collaboration, users might not have forks of all required repos. This caused a misleading request to use a password to login to github rather than an error for a non existing repo. This PR checks all repos with git -ls-remote and if one or more are missing quits with a list of missing repos
=> check if git repo exist to avoid weird errors when users build their own

utils/singularity/copy_to_target_area.pl, utils/singularity/create_index_html.pl
This PR adds the /opt/sphenix/utils tarball. It is not needed to run reconstruction but it contains development utilities (cppcheck, valgrind,...) which are useful to have
=> Add /opt/sphenix/utils

utils/rebuild/packages.txt
Hmm.... Have to reverts sPHENIX-Collaboration/utilities#59  The INTT lib still depends on g4intt in the current coresoftware prior to Tony's tracking reorganization: https://github.com/sPHENIX-Collaboration/coresoftware/pull/614 
Currently it breaks the build: https://web.racf.bnl.gov/jenkins-sphenix/job/sPHENIX/job/sPHENIX_CoreSoftware_MasterBranch/168/
=> Revert "Trackbase implementation"

utils/rebuild/packages.txt
the PR moves the build of g4dst to the end. It is just a convenience library which loads all libraries from our DSTs so you only have to load this one to read DSTs without problems
=> g4dst needs to be build last

utils/rebuild/build.pl
This PR fixes an error in jenkins. getlogin does not seem to return anything on the jenkins machine, this sets the username to "jenkins" if getlogin does not return anything. This is not critical, action is only taken if the account is phnxbld in which case the git tag of the build is stored in a DB
=> getlogin returns nothing on jenkins, use jenkins as username

utils/rebuild/build.pl
This PR enables the build with clang. This needs a change in a stdc++ header (include/bits/hashtable_policy.h). We will have a special machine for this (and likely patch jenkins with this, it does not affect the gcc compilation)
=> Add --clang to build with clang instead of gcc

utils/rebuild/clang_build_singularity.csh
This PR adds a small shell script to call the build with clang. clang needs a modified include file /usr/include/c++/4.8.2/bits/hashtable_policy.h which is mounted from our cvmfs repo. The binaries do not need this include to run (also gcc is fine with that modification but we do not want to push this out for all users of rcf).
=> build clang inside singularity container which mounts modified include

utils/rebuild/clang_build_singularity.csh
The odbc.ini file is under /sphenix/user/odbc - we cannot put it into cvmfs which is world readable. In order to access it from the build script which puts the git tags into the DB /gpfs and /sphenix need to be mounted
=> mount /gpfs and /sphenix to get to the odbcini file

utils/rebuild/packages.txt
This PR removes the g4hough from the package list and the ancient commented out phfield
=> remove build of g4hough

utils/rebuild/build.pl
This PR just replaces the previous play package replacements with the new version of fastjet for testing
=> use fastjet 3.3.2 (with fjcontrib 1.042) in play build

utils/rebuild/build.pl
This PR adds KFParticle (which depends on the root version) and Vc needed by KFParticel to OFFLINE_MAIN. KFParticle unfortunately dumps all its header files into the include directory without package path, so all this gets dumped to OFFLINE_MAIN/include. We should change that at some point
=> Add KFParticle to packages copied to OFFLINE_MAIN (and with it Vc)

utils/rebuild/build.pl
pythia8243 seems to work - no segfaults in 1000 tests. This PR switches the play build to the optimized version
=> use new pythia8 version compiled with optimization on

utils/rebuild/clang_includecheck_singularity.csh
This PR adds a script to run the clang based include check in a container. The stock gcc version in SL7 uses a buggy include file which is needed by clang. The fixed version of this include is mounted in the container so clang works
=> run include check in container

utils/rebuild/build.pl
This PR sets the -l in make to the number of cores. I did some reading what the load actually means, it is basically the number of busy cores though the disk activity goes into this number as well. That means up to a load of the number of cores there are idle cores which should be used. The previous 8 was definitely too low for our new build machines
=> adjust load limit in make to number of cores

utils/rebuild/build.pl
This PR introduces the "old" build where the previous 3rd party packages are used. Also install tbb now by default to OFFLINE_MAIN
=> adjust packages for old build, copy tbb by default to offline_main

utils/rebuild/build.pl
This PR enables to set the sysname in case you don't want the afs sysname. Default is still the afs sysname which also replaces the one hardcoded x8664_sl7 we had. Sorted the options alphabetically when printing help
=> Add sysname as option for gcc-8.3

utils/rebuild/build.pl
This PR prepares the build script for the play build under gcc 8.3 using the newest G4 version (10.06) which does not build with gcc 4.8.2
=> gcc 8.3 play build uses g4 10.06, needs other clhep version

utils/rebuild/build.pl
This PR adds a -1 return value if the build fails. That should make Jenkins's job easier to spot build failures
=> return -1 on failure

utils/singularity/copy_to_target_area.pl
This PR enables copying of other compiler versions than x8664_sl7. The respective tar.bz2 files are now copied into subdirectories (sysname/build) to keep them separate
=> Copy gcc 8.3

utils/rebuild/build.pl
This PR copies the newest gsl version (2.6) to OFFLINE_MAIN for the play build
=> use new gsl lib for play build

utils/rebuild/build.pl
Now a satre_<rootversion> softlink points to the sartre installation so we can have multiple sartre versions
=> remove version from sartre

utils/rebuild/build.pl, utils/rebuild/scan-build_singularity.csh
This PR writes a correct index.html if there are no scan-build errors (highly unlikely) and adds a script to run it inside a container for gcc 4.8.2 bc the compiler bug which prevents the usage of clang
=> Finalize scan build

utils/rebuild/build.pl
This PR just adds using gsl-2.6 instead of the default for test builds
=> Add different external packages for test version

utils/rebuild/build.pl
This PR makes the softlinks consistent with /opt/fun4all. Needed for local copies which are restores as /opt/fun4all
=> rename softlinks to root and G4 from /opt/sphenix to /opt/fun4all for --eic

utils/singularity/copy_to_target_area.pl
small bugfix to change the softlink names from /opt/sphenix to /opt/fun4all so it matches the downloaded directory structure
=> fix softlink names from sphenix to fun4all

utils/rebuild/build.pl
libgenfit.so is either in lib or lib64 depending on the genfit installation. This PR now rsyncs the lib dir it finds. Also replace $HOST by hostname -s which works with bash ($HOST is only known to tcsh)
=> rsync lib and lib64 for genfit package

utils/rebuild/packages.txt, utils/rebuild/repositories.txt
This PR replaces acts-framework by acts in the package and repositories
=> build acts, not acts-framework

utils/rebuild/eic-packages.txt, utils/rebuild/eic-repositories.txt
This PR just updates the eic build with the new acts repo instead of acts-framework
=> check out new acts repo instead of acts-framework

utils/rebuild/build.pl
This PR fixes the build with include-what-you-use. With the clang upgrade to 9.0.1 clang uses its own system headers and it needs a -I/opt/sphenix/utils/lib/clang/9.0.1/include for include-what-you-use to find them
=> include-what-you-use needs path to clang system includes

utils/rebuild/clang_includecheck_singularity.csh
This PR is a small fix. include-what-you-use is based on clang and therefore the sources need to be configured using clang. So far they are configured using gcc which leads to different suppressions of warnings which then prevent include-what-you-use from compiling those sources
=> configure sources using clang

utils/rebuild/build.pl
The latest change used $myhost=`hostname` so this works under bash where $HOST is not defined. Sadly this adds a crlf to $myhost which messed you the string which tells tinderbox what kind of build it is dealing with. A simple chomp $myhost takes care of that
=> strip crlf from hostname

utils/rebuild/build.pl, utils/rebuild/eic-packages.txt, utils/rebuild/packages.txt
This PR enables the build to ignore missing packages. This means we can add new packages to our build (so jenkins can run over it) without crashing every other build while the new package is being evaluated.
Also adding Dmitry's PHTpcTracker to the build
=> Ignore missing package

utils/rebuild/build.pl
the build script aborted on failure before informing tinderbox which also prevented the logs from getting into tinderbox. This PR fixes this behavior (it also un-chatters sendmail so I do not get any mails from the cron jobs with the mail log)
=> fix tinderbox when build is busted

utils/rebuild/build.pl
This PR set the return code back to a negative value on failure so jenkins can react to failed builds again
=> set failure return code to -1 via POSIX::_exit(-1)

utils/rebuild/build.pl, utils/rebuild/eic-repositories.txt
This PR installs root macros from macors/common to $OFFLINE_MAIN/rootmacros. Next step will be to add this to the root include path so we can use common macros and keep detectors separate instead of piling everything into a single directory
=> Install rootmacros

utils/rebuild/build.pl
This PR copies HEpMC3 to $OFFLINE_MAIN. Right now it is only being used by the latest eic-smear version but we'll need it for jetscape if this gets off the ground
=> install HepMC3

utils/rebuild/build.pl
This PR changes the version symlinks to relative links. So far e.g. new pointed to /cvmfs/sphenix.sdcc.bnl.gov/x8664_sl7/release/release_new/new.3. That is no problem for running with cvmfs but local builds with a mounted cvmfs filesystem got confused and pointed you back to cvmfs. This PR now creates new -> new.3 so this stays within the same filesystem
=> use relative symlink for build version (e.g. new -> new.4)

utils/rebuild/rsync-build.pl
This PR adjusts the script which rsyncs builds (from sdcc.bnl.gov to opensciencegrid.org) for the new short version number softlinks introduced yesterday
=> adjust for new short softlink for build number

utils/rebuild/build.pl, utils/rebuild/eic-packages.txt, utils/rebuild/packages.txt
Finally update package maintainers (a few of them have left years ago), replace links pointing to www.phenix.bnl.gov to phenix internal webserver phenix-intra.sdcc.bnl.gov
=> Fix maintainers

utils/rebuild/build.pl
So far the build was aborted if an external package was missing. Now we probably will have separate packages for the eic and sphenix so there will be missing packages by default
=> just continue if an external package is missing

utils/rebuild/build.pl
cmake needs some more convincing to use ccache - it refuses to use the path for the compiler. It needs to be called with -DCMAKE_CXX_COMPILER=`which g++`. This is now used when CCACHE_DIR is set. Setting -DCMAKE_CXX_COMPILER doesn't hurt if ccache is not enabled but I'd rather leave the default sane
=> build acts with ccache if CCACHE_DIR is set

utils/rebuild/build.pl
This PR fixes a warning about a one time use of CCACHE_DIR - not it is printed into the log. Adds the ccache C compiler in case another cmake package needs it
=> Add C compiler setting, print out CCACHE_DIR

utils/rebuild/packages.txt
This PR adds the FermiMotionAfterburner to the build (so jenkins actually compiles it)
=> add coresoftware/generators/FermiMotionAfterburner to build

utils/singularity/utils_no_tar.list
add outdated package to list of packages which are not copied to offline tar ball
=> do not copy ccache-3.6 to tar ball

utils/rebuild/build.pl
This PR adds compilation with insure to ACTS. cmake needs a bit of convincing to actually do this but a temporary shell script with the command line does the trick
=> Compile ACTS with insure for --insure

utils/rebuild/eic-packages.txt, utils/rebuild/packages.txt
This PR moves the ffamodules. The new header reco needs to catch the simulation information which is read in by phhepmc (or created by the event generators)
=> move ffamodules behind phhepmc to catch sim info

utils/rebuild/eic-packages.txt
This PR fixes a build problem for the eic (needs the fermi motion to load G4_Input.C)
=> add FermiMotionAfterburner to eic-packages.txt

utils/rebuild/build.pl
include what you use needs the path to the corresponding clang installation for the include files. I guess I could extract it from the clang version. Maybe next time. At least include what you use now works in the gcc 8.3 environment
=> upgrade IWYU to clang 11.1.0

utils/rebuild/ecce-packages.txt, utils/rebuild/eic-packages.txt, utils/rebuild/packages.txt
This PR removes the raw data related packages phoolraw and fun4allraw temporarily from the build. These packages will be fixed in a subsequent PR. This way all crashed jenkins jobs for existing PRs should just go through
=> remove raw data related packages temporary from build

utils/rebuild/ecce-packages.txt, utils/rebuild/eic-packages.txt, utils/rebuild/packages.txt
The raw data packages were switched from ogzBuffer to ospBuffer and are ready to be build again
=> put raw data packages back in the build

utils/rebuild/ecce-repositories.txt
This PR adds the ecce fork of the eic macros to the build
=> add fun4all_eicmacros which now contains the eic macros

utils/rebuild/ecce-packages.txt, utils/rebuild/eic-packages.txt
This PR adjusts the package files for the moving of the g4 sim packages in the fun4all_eicdetectors repo
=> move g4 sim packages under simulation/g4simulation

utils/rebuild/build.pl
This PR makes a small mod - the new DD4hep version is used for the play build, tpc-rs is not used - it is not copied anymore
=> Add new DD4hep version to play build, remove unused tpc-rs

utils/rebuild/build.pl, utils/rebuild/ecce-repositories.txt, utils/rebuild/eic-repositories.txt
This PR enables the use of multiple calibrations repos (all repos with 'calibrations' in their name). The files are rsynced to their final destination. The problem of duplicate filenames is not addressed, last repo in the list wins - please be mindful of this
=> Multiple calib repos

utils/rebuild/build.pl
The tagging of the calibrations was still done in cvmfs where they were checked out after the build. Now they are rsynced from the initial checkout. The special afterburner is not needed anymore (and it created error messages)
=> calibrations are rsynced, handle same way as other git repos

utils/rebuild/build.pl
The PR just moves the beast magnetic field reader from external packages to root based external packages
=> beast magnetic field reading depends on root version

utils/rebuild/ecce-repositories.txt
Similar to the macros repository, the ECCE calibration repository will switch to independent calibrations repository and use a single calibration repository model. 
This is part of the change as the ECCE simulation is rebuilt with June-2021 detector concept
=> ECCE switches to independent calibrations repo

utils/rebuild/build.pl
The new place for large calibrations (the ones we do not want or cannot commit to git) is now in cvmfs ($OPT_SPHENIX/calibrations). It has the same subdirectory approach as the git based calibration files. In order to save space in cvmfs, it creates a softlink rather than copying the files over
=> create softlinks to calibrations in cvmfs core/calibrations

utils/rebuild/build.pl
This PR changes the play build - it now uses the latest HpeMC3 version (3.2.4)
=> make play build with HepMC3 3.2.4

utils/rebuild/build.pl
This PR adds hdf5 to our external packages. It's tested and working - so users do not have to tweak their paths to use it anymore.
=> add hdf5 to external packages

utils/rebuild/build.pl
This PR remedies a problem we have for ana or mdc builds. They release a top dir which can take a longtime to sync and they often run into the 30 minute timeout.
This PR extends the timeout for the cvmfs release to 3 hours. Even if the timeout is exceeded the build ends with success so the git tags are saved in the DB. We still have a protection in case the previous build is hanging.
=> succeed even if release times out (3 hours now), cvmfs can take a long time

utils/singularity/utils_no_tar.list
This PR removes the old valgrind and cppcheck versions from the uti tarball
=> update for latest valgrind and cppcheck versions

utils/rebuild/build.pl
This moves the coverity and scan-build html output on the internal sPHENIX webserver, so non PHENIX users can see them
=> use the sPHENIX webserver for scan build and coverity html output

utils/rebuild/build.pl, utils/rebuild/eic-packages.txt, utils/rebuild/eic-repositories.txt
This PR adds special handling for the temporary g4test build, just to have something which works with the new G4 version until things are sorted out. renames the eic fun4all_acts back to acts
=> Add g4test

utils/rebuild/packages.txt
This PR removes the obsolete eic physic list from the build packages
=> remove eic physics list from build

utils/rebuild/build.pl
I reorganized some of our 3rd party packages. Most event generators now depend on the root version via their hepmc3 dependency, so they are now root packages with the root version appended to their installation directory. For older packages this is taken care off by properly named softlinks. The play build now uses the newest root and G4 version (where the new root version is build with the old tbb version so our default acts builds with it)
=> play build with new root+G4, reorganize 3rd party packages

utils/rebuild/build.pl
This PR switches us to the 3rd party packages of the new acts version. Needed before submitting the PR which adjusts the core software. The current "new" build will be build as "old"
=> move new build to old, remove special for test build, that is default now

utils/rebuild/build.pl
The build script pulled in a boost patch for clang compilation. For the new boost version 1.78 this is not needed anymore. Also adjusted the 3rd party packages to keep the play build as is
=> Play build

utils/rebuild/build.pl
combining dd4hep with acts killed the insure build in December. cmake does really not play well with insure, these changes make it work somehow with the new acts, root and g4 version
=> get insure build to work again (probably can be streamlined)

utils/rebuild/build.pl
This PR is for the new play build which uses G4 11.00.01 (needs updated DD4hep-01-20-01_geant4-11.00.01)
=> play uses G4 11.00.01, needs special dd4hep version

utils/rebuild/packages.txt, utils/rebuild/qa-packages.txt
This package is outdated and it does not link with the current xpload. Might come back at some point but for now stop building it
=> comment out dbtools

utils/rebuild/build.pl
This PR now uses G4 10.06.p03 for the G4 version (down from G4 11)
=> use G4 10.06.p03 for g4test build

utils/rebuild/packages.txt
PHParameter now has a dependency on ffamodules via the xpload interface
=> offline/database/PHParameter now needs offline/framework/ffamodules

utils/rebuild/rsync-build.pl
The script now prints a warning to stdout on error so the cron will send an email. This script has been failing since May 5th and nobody noticed.
=> print failure warning to trigger crontab email

utils/singularity/utils_no_tar.list
This PR drops cppcheck 2.6 from the utils tar ball
=> exclude cppcheck-2.6 from utils tar ball

utils/rebuild/build.pl
This PR builds acts for all options at install-headers. insure has been dying for a log time, leaving la files takes care of that
=> build all versions acts at install, leave la files for insure

utils/rebuild/build.pl
The make install for acts was missing for the scan build, fixed in this PR
=> fix the scan build (make install for acts was missing)

utils/rebuild/build.pl, utils/rebuild/packages.txt
This PR makes the scan-build using clang 14 functional (the location had a hardcoded llvm-11 in the path). Remove copying of the obsolete sartre to OFFLINE_MAIN, remove PHTpcTracker from build (nothing linked against it)
=> Scan build clang 14

utils/rebuild/build.pl
This PR prepares for the move to gcc 12. Make root 6.26.06 the default
=> use root 6.26.06 for default for gcc 12, root 6.24.06 for old

utils/rebuild/build.pl
This PR sets the number of new builds to 10 before they roll over
=> set maximum builds to 10 before roll over

utils/rebuild/build.pl, utils/rebuild/packages.txt
This PR adds the build type and os to the subject line of the crash mails. Makes it easier to figure out which build went wrong
=> Crashmail explicit

utils/rebuild/build.pl
the include what you use compilation still used clang 11 includes which made it croak. Fixed now
=> fix make arg for iwyu

utils/rebuild/packages.txt
This PR adds the cdb client library back under sphenixnpc (sphenix no payload client) for the upcoming PR
=> Add coresoftware/offline/database/sphenixnpc|pinkenburg@bnl.gov

utils/rebuild/build.pl, utils/rebuild/packages.txt
Xpload is obsolete - remove from copying to offline, db_file_accessor is replaced by CDBTTree
=> remove xpload and db_file_accessor

utils/rebuild/packages.txt
This PR adds the mbd to prepare for a rename of bbc -> mbd. It does not matter if a package does not exist, the build will just skip it (and complain a bit)
=> add mbd to be able to rename bbc -> mbd

utils/rebuild/build.pl
The repotags hash map was only filled after the rebuild.info was written, now fill repotags before writing rebuild.info
=> fill repo tags hash before writing info file

utils/rebuild/build.pl
With heavy load on our file catalog, we cannot connect to the server sometimes. This adds a retry mechanic which sleeps 10-31 secs and then retries (100 times, before giving up)
=> sleep and retry if DB connection failure

utils/rebuild/build.pl
This PR fixes another warning by a print statment in the DB retry
=> another warning cropped up

utils/rebuild/build.pl
This PR installs Herwig under $OFFLINE_MAIN, needed a tweak for Herwig installing its libraries under lib/Herwig
=> add Herwig to 3rd party packages

jenkins/built-test/clang-tidy.sh
This PR adds -DHomogeneousField and -Wno-dangling to the clang-tidy flags to process all sources in offline/packages/tpccalib and KFParticle_sPHENIX
=> Add flags to clang-tidy

utils/rebuild/packages.txt
Move QA utility order up to allow use of QA stuff everywhere in Fun4All
I am working on TPC code in `fun4allraw`, and realized that the internal workings of `fun4allraw` could use some formal QA there, e.g. QA histogram built as events are unpacked and assembled together, before they hit the DST. This PR will allow such wide use of QA, as long as it is using Fun4All framework (and therefore built after `fun4all` lib).
=> Move QA utility order up to allow use of QA stuff everywhere in Fun4All

utils/rebuild/build.pl
I updated the psqlodbc driver yesterday, it seems to reject the unix timestamp used for the date. This PR now uses a time stamp which works with the new driver
=> new odbc driver needs different date format

utils/rebuild/packages.txt
caloTreeGen was not build bc the wrong location in packages.txt. Moved it to offline/packages which is more logical better place
=> move caloTreeGen to packages

utils/rebuild/build.pl
This PR removes the special handling of the nopayloadclient, insure can now deal with the optimized nopayload build
=> no special nopayloadclient for debug

jenkins/built-test/cpp-check.sh
nanoflann.hpp generates a syntax error warning which can't be fixed. using --suppress=syntaxError in the cmd line suppresses those errors
=> add --suppress=syntaxError to cppcheck args to remove perceived syntax errors

utils/rebuild/packages.txt
Move kfp down in the package list to be below the trigger object and beyond the tracking reconstruction
=> fix: move kfp

utils/rebuild/build.pl, utils/rebuild/packages.txt
This adds the Herwig jet trigger package. Cleanup: remove installation of bzip2 (now part of alma9) and pythiaeRhic (does not build anymore)
=> Add herwig

utils/rebuild/build.pl
There is a danger for long running condor jobs (10 days right now) to run beyond the rollover of the new builds (10 days). This PR increases the number of builds before rolling over to 20
=> increase number of new builds to 20
