sPHENIX-Collaboration/utilities

utils/rebuild/packages.txt
Insert the new g4bbc library into the build.
=> add g4bbc to build

utils/rebuild/packages.txt
just making sure this is the last library to be build
=> move g4dst to the end of the build

utils/rebuild/build.pl
we have a bunch of packages which are linked against a special root version. This causes some real pain when test building a new root version before switching.  Those packages are now installed as <package>_root-<version>. The build script checks the root version via root-config --version and creates the package name based on this.
=> handle external packages which depend on root version

utils/rebuild/packages.txt
=> Add PHSartre

utils/rebuild/packages.txt
just adding g4tpc to packages.txt
=> add tpc to nightly build

utils/rebuild/packages.txt
Updates following https://github.com/sPHENIX-Collaboration/coresoftware/pull/405
=> Relocating the parameter IO utilities for use by wider set of packages

utils/rebuild/packages.txt
I tried to assign the appropriate person to get the mails from each of Mikes packages
=> replace Mike McCumber

utils/rebuild/build.pl
that didn't work again. Lets try this
=> try the logfile again

utils/rebuild/build.pl
This has been tested for a while now, by default this script installs in cvmfs. If build.pl --afs is used it installs in afs. The cron jobs on phnxbld have been updated accordingly
=> Cvmfs enabled build script

utils/rebuild/build.pl
added rapidjson to 3rd party packages which get copied to OFFLINE_MAIN
=> copy rapidjson to OFFLINE_MAIN

utils/rebuild/build.pl
=> opt_source parameter appears missing

utils/rebuild/build.pl
We have occasional issues with removing the install directory of the nfs mounted cvmfs filesystem on cvmfswrite01/02. This could come from the scanning of the tree for a release file. This PR does a retry of this after 10secs which should be sufficient to deal with this if the scanning is the reason.
Also included in the PR is the replacement of rmtree and mkpath which have been obsolete for a while by their replacement remove_tree and make_path
=> retry after 10 secs if rm of isntalldir fails bc open files

utils/rebuild/packages.txt
add the proposed EIC physics list which incidentally covers sPHENIX energies
=> Add EICPhysicsList

utils/rebuild/build.pl
add forgotten help for --gitbranch, so we do not forget this option exists
=> add gitbranch printout

utils/singularity/copy_to_target_area.pl
create tarballs for singularity distribution and copy them to a target dir
=> Singularity scripts

utils/singularity/create_index_html.pl
just so we don't have to worry to leave dangling links. Not nice but will do the job for starters
=> create index.html from what we find, not hardcoded

utils/singularity/copy_to_target_area.pl
oops, tried to copy a non existing file which did not go well
=> index now generated

utils/rebuild/build.pl, utils/rebuild/repositories.txt
the gittag from git show is now saved in rebuild.info in the install area. Added macros and utilities repository so we save their tags as well
=> Save gittag

utils/rebuild/build.pl
That should be the last one for the time being.
=> add calibrations repo to info file

utils/rebuild/build.pl
the PR puts the git tags from the cloned repos into a DB from where they can be retrieved anytime. This is only enabled for the phnxbld account - other users running that script won't affect the DB content. It stored the tags for all our builds, if the release number rolls over (or the same build is done twice to e.g. recover from a crash), the info for the previous build gets wiped
=> save git tags in DB

utils/singularity/create_index_html.pl
the new build is root6 based now, root5 is in the root5 subdir
=> new is root6 now, root5 is root5

utils/rebuild/packages.txt
Change to build package order to accompany coresoftware PR#614.
=> Trackbase implementation

utils/rebuild/packages.txt
=> tpc,mvtx and intt lib need to be build before their g4 correspondants

utils/rebuild/build.pl
This PR adds an option to run the include checker
=> Add running clang basedinclude checker

utils/rebuild/build.pl
I have upgraded a bunch of 3rd party packages for a move to a new root version. This PR adjusts the play build to install them.
=> play build for test with upgraded packages

utils/rebuild/analyze_includecheck_log.pl
This PR just adds a few more includes which are ignored by the log analysis
=> update ignore lists

utils/rebuild/build.pl
The play build for the latest G4 version 10.05.p01 needs these external packages
=> pull in external packages for new G4 10.05.p01

utils/rebuild/packages.txt
This PR adds simulation/g4simulation/g4jleic for JLab eic detectors
=> add g4jleic for JLab detector

utils/rebuild/packages.txt
This PR adds 2 new directories to build (phoolraw and fun4allraw) which separates the raw data handling from the rest
=> move raw data handling to separate raw directories

utils/rebuild/rsync-build.pl
This PR sets the root and geant4 softlink correctly to the installation on the current cvmfs volume
=> set root and geant4 softlinks correctly

utils/singularity/create_index_html.pl
This PR add the link for the virtual box image (hardcoded) so it does not get overwritten by the cron
=> Add link for virtual box image

utils/singularity/create_index_html.pl
This PR adds a line what to do if prompted for login
=> Add login doc for fun4all container

utils/rebuild/build.pl
This PR copies the newly build acts-core to offline_main
=> add copying of acts if packages exists (it does not for x8664_sl7)

utils/singularity/create_index_html.pl
This adds the download of the docker image to the html index
=> Add entry for docker image

utils/rebuild/build.pl, utils/rebuild/repositories.txt
This PR adds the copying of ACTS-framework to OFFLINE_MAIN, building it is next
=> Add acts-framework to repos, copy acts-framework to OFFLINE_MAIN

utils/rebuild/build.pl
This PR checks out the sphenix-v0.13.00 of acts-framework which we use
=> clone sphenix-v0.13.00 branch of acts-framework

utils/rebuild/build.pl, utils/rebuild/packages.txt
This PR adds acts-framework to the nightly build (for gcc 8.3). It checks out the sphenix-v0.13.00 branch
=> Add building of acts-framework, needs special treatment for use of cmake

utils/rebuild/build.pl
This PR puts the scan-build back in. The reports are put on https://www.phenix.bnl.gov/WWW/p/draft/phnxbld/sphenix/scan-build/scan
=> fix up scan-build

utils/rebuild/build.pl
This PR enables a full debug build (including acts-framework which needs build type in cmake)
=> build debug acts-framework for version=debug

utils/rebuild/build.pl, utils/rebuild/scanbuild_ignore.txt
This PR just adds -plist-html to the scan-build args so jenkins can analyze the output
=> Plist html

utils/singularity/copy_to_target_area.pl, utils/singularity/create_index_html.pl
This PR adds to taring and copying of the MCEG area under x8664_sl7
=> add copying of MCEG (rough but works, no error checking)

utils/rebuild/eic-packages.txt, utils/rebuild/eic-repositories.txt
Add the new fun4all_eicdetectors repo
=> Add fun4all_eicdetectors

utils/rebuild/build.pl
This PR adds the tinderbox to the EIC builds, they go to /phenix/WWW/offline/EIC/, also prepare coverity and scan builds for EIC
=> Tinderbox eic

utils/singularity/copy_to_target_area.pl, utils/singularity/create_index_html.pl
This PR adds what is needed to tar up the EIC cvmfs volumes
=> copy the EIC builds, create eic html index

utils/singularity/copy_to_target_area.pl, utils/singularity/utils_no_tar.list, utils/singularity/utils_restow.list
This PR strips the utils tar ball drastically. llvm is huge and nobody really needs it. Also obsolete packages were still tarred up
=> Tar opt utils

utils/rebuild/eic-repositories.txt, utils/rebuild/repositories.txt
This PR adds the calibrations repo so its tag gets stored in the DB as well
=> Add calibrations to repositories

utils/rebuild/build.pl
The PR removes the la files from 3rd party libs which are copied to $OFFLINE_MAIN/lib. They are not needed but often throw libtool off insisting on the wrong library
=> remove the *.la files from 3rd party libs

utils/rebuild/build.pl
=> oops - % instead of %s

utils/rebuild/build.pl
This PR builds the new ACTS version from github (the sPHENIX branch)
=> build new acts version from github

utils/rebuild/eic-packages.txt, utils/rebuild/packages.txt
The build order needs changing
=> PHTpcTracker needs PHGenFitPkg

utils/rebuild/build.pl
This PR removes the G4 examples from the acts build
=> remove GEANT4 from acts build

utils/singularity/create_index_html.pl
This PR uses relative paths as links, absolute paths do not work in the new location (and are stupid anyway)
=> use relative paths for links files, not disk locations

utils/rebuild/eic-packages.txt
This PR adds the micromegas to the eic build
=> add micromegas

jenkins/built-test/test-tracking-qa-gallery-thumbsup.json, jenkins/built-test/test-tracking-qa-gallery-thumbsup.sh, jenkins/built-test/test-tracking-qa-gallery.sh
This PR adds the new QA gallery website generator using thumbsup and some naming convention issues for the vertex and DCA plots in this new generator and the old sigal generator
=> New QA plot gallery generator

utils/rebuild/eic-packages.txt, utils/rebuild/packages.txt
This PR adds ffamodules to the packages. It is needed to avoid circular dependencies
=> Add offline/framework/ffamodules

utils/rebuild/build.pl
one more small fix - create mdc softlinks in top release dir, just like for ana and pro
=> create new softlink for mdc build in relase top dir

utils/rebuild/eic-packages.txt, utils/rebuild/packages.txt
This PR adds Camerons KFParticle code to our build
=> add offline/packages/KFParticle_sPHENIX

utils/rebuild/build.pl
This PR uses HepMC-2.06.11 for the play build for testing
=> use HepMC-2.06.11 for play build

utils/rebuild/build.pl
This PR adds a default repo owner to the build script. If you use a different owner - that owner has to have a fork of all relevant git repos (coresoftware,macros,calibrations,prototype, utilities). Now the build script checks if a repo exists for a given owner - if not it falls back to the default (sPHENIX-Collaboration)
=> use default repo owner if repo under new owner does not exist

utils/rebuild/build.pl
This PR adds an option to set the branch for the acts repo, needed for tests of new acts version. Also finally creatign a softlink in the include dir Eigen -> eigen3/Eigen so we can get rid of those -I$(OFFLINE_MAIN)/include/eigen3 in our Makefile.am's (or at least do not have to add new ones)
=> add option for acts branch, softlink Eigen -> eigen3/Eigen

utils/rebuild/build.pl
This PR adds acts to the sources which are compiled with clang - previous clang version installed under x8664_sl7 did not understand c++17
=> compile acts with clang

utils/rebuild/build.pl
It turns out clang needs a patch for boost while this patch crashes gcc. The build now copies the patch from cvmfs only for compiling with clang. Fixed options for scan-build which came with clang 11, we can now run scan build under gcc 8.3. The clang patch needs a cvmfs release but the release seems to have gone belly up when adding this. The build script runs on cvmfswrite02 which has cvmfs locally mounted, the build should succeed on it
=> add copying boost patch for clang

utils/rebuild/build.pl, utils/rebuild/ecce-packages.txt, utils/rebuild/ecce-repositories.txt
This PR adds the capability to build the ecce version separate from the eic
=> Ecce build

utils/rebuild/eic-packages.txt, utils/rebuild/eic-repositories.txt
This PR cleans up the eic packages, no effect on sPHENIX
=> remove g4hakanvtx, add fun4allgdmlimport

utils/singularity/copy_to_target_area.pl, utils/singularity/utils_restow.list
This PR adds the capability to tar up subdirs (like ecce)
=> Copy ecce areas

utils/singularity/copy_to_target_area.pl
add the default softlink to the checkout, tar up fieldmap
=> tar up default softling and fieldmaps

utils/rebuild/ecce-packages.txt, utils/rebuild/ecce-repositories.txt, utils/rebuild/eic-packages.txt, utils/rebuild/eic-repositories.txt
This PR updates the repo and package list for eic and ecce
=> adjust packages and repos for new split

utils/rebuild/ecce-repositories.txt
=> Merging eicmacros to macros for ECCE

utils/rebuild/build.pl, utils/rebuild/packages.txt
This PR changes the play build to use the new boost and tbb version (with a new root version) needed for the ACTS upgrade
=> New play build

utils/rebuild/build.pl
This PR adds a special treatment for the current test build for the new acts version
=> treat test build like play build for 3rd party packages

utils/rebuild/packages.txt
This PR adds Christof compressor package
=> Add Christofs compressor package

utils/rebuild/ecce-packages.txt, utils/rebuild/eic-packages.txt
This PR makes Friederike the recipient of build mails for the drcalo
=> Drcalo maintainer

utils/rebuild/build.pl
This PR adds pytorch to the 3rd party software to be copied
=> install pytorch under OFFLINE_MAIN

utils/rebuild/ecce-packages.txt, utils/rebuild/eic-packages.txt
This PR adds the building of fun4all_eicdetectors/simulation/g4simulation/g4zdc for eic and ecce
=> add g4zdc to packages

utils/rebuild/rsync-build.pl
With softlinks now also used for big calibration files, softlinks need a more generic treatment when copying builds to other cvmfs volumes. This PR replaces the previous explicit change of the root and geant4 softlink by a search for softlinks and replacing the ones which point to the source volume
=> replace explicit softlink renaming to search and replace

utils/rebuild/packages.txt
This PR adds the pi zero calibration package to the build
=> add pi0 cal code

utils/rebuild/ecce-packages.txt, utils/rebuild/eic-packages.txt, utils/rebuild/packages.txt
Now I will get the mails for PHTpcTracker
=> remove Dmitry from PHTpcTracker

utils/rebuild/packages.txt
For https://github.com/sPHENIX-Collaboration/coresoftware/pull/1300
=> add `coresoftware/generators/decayFinder|cdean@bnl.gov`

utils/rebuild/ecce-packages.txt, utils/rebuild/eic-packages.txt
Sorry Chris, we're just merging this package now and it wasn't in the build before
=> Added Roman Pot full sim

utils/rebuild/packages.txt
This PR adds offline/packages/centrality and simulation/g4simulation/g4centrality to our packages. Needs to be merged before jenkins is run
=> add centrality packages

utils/rebuild/packages.txt
This PR adds a new package - dbtools to start work with our new conditions DB
=> add coresoftware/offline/database/dbtools|pinkenburg@bnl.gov

utils/rebuild/build.pl
This PR builds ACTS with dd4hep and G4 interfaces and examples enabled
=> build acts with dd4hep and G4

utils/rebuild/build.pl, utils/rebuild/eic-packages.txt
This PR creates coverity and scan-build builds for ecce and eic
=> Eic coverity

utils/rebuild/build.pl
This PR builds the new acts version (15.0.1) from the acts repo for play builds
=> build acts rom acts repo for play build

utils/rebuild/build.pl
This PR is for the eic build so we can keep using the sPHENIX version of the acts repo
=> add option for separate acts repo owner

utils/rebuild/packages.txt
This PR adds a new package which is used as a DB interface to CaloReco
=> Add calibrations/calorimeter/dbfile_accessor_calo|frantz@ohio.edu before CaloReco

utils/rebuild/packages.txt
This PR adds the Fun4All Event combiner
=> add ffarawmodules package with event combiner

utils/singularity/copy_to_target_area.pl, utils/singularity/create_index_html.pl
The new singularity container has a .sif extension, needed to update these scripts with it
=> use new singularity container rhic_sl7_ext.sif

utils/rebuild/build.pl, utils/rebuild/qa-packages.txt, utils/rebuild/qa-repositories.txt
This is for the occasional build for the Fun4All QA group
=> Add eic qa build

utils/rebuild/qa-packages.txt
It now needs g4hits which was downstream
=> Moving decay finder to offline/packages

utils/rebuild/packages.txt
This PR adds Ejiros event plane module. It is still a draft but this way jenkins runs over it
=> Add coresoftware/offline/packages/eventplane|ejironaomiumaka@gmail.com

utils/rebuild/build.pl
This PR adds onnxruntime to the installed 3rd party packages
=> install onnxruntime under OFFLINE_MAIN

utils/rebuild/packages.txt
This PR adds TrackerMillepedeAlignment to the package list
=> add coresoftware/offline/packages/TrackerMillepedeAlignment to packages

utils/rebuild/build.pl, utils/rebuild/packages.txt
This adds the new offline/database/cdbobjects to the build
=> Cdbobjects

utils/rebuild/build.pl
rootcint uses the ROOT_INCLUDE_PATH to locate includes when it cannot find them via the regular -I. This PR resets the ROOT_INCLUDE_PATH so includes from another build cannot leak into the current build. Dictionaries which include Acts includes relied on this mechanism, so now Acts is installed before other packages call install-data which triggers the dictionary generation. Acts call make clean for non regular builds (coverity, scan, insure) so it gets build again with the proper flags
=> set ROOT_INCLUDE_PATH to $OFFLINE_MAIN/include

utils/rebuild/build.pl
This PR adds LHAPDF to our installed packages - Herwig needs it
=> Add LHAPDF6 to third party installs

utils/rebuild/packages.txt
sartre is a headache to build, it is an electron ion generators which sounds like a problem the eic software will have to deal with
=> sartre is electron ion generator

utils/rebuild/packages.txt
This PR adds the bbc software to our package list which will be committed soon
=> add offline/packages/bbc

utils/rebuild/packages.txt
This PR adds the g4tracking package in preparation for a PR to add this
=> add coresoftware/simulation/g4simulation/g4tracking|0ds.johnny@gmail.com

utils/rebuild/packages.txt
Add package to test against https://github.com/sPHENIX-Collaboration/coresoftware/pull/1903
=> Add tpc hit event display package

utils/rebuild/packages.txt
That needs some more doing to compile with clang, commenting it out so it does not crash jenkins
=> comment out sphenixnpc

utils/rebuild/packages.txt
ffamodules depend on sphenixnpc
=> move sphenixnpc ahead of ffamodules

utils/rebuild/packages.txt
Adds new globalvertex package to list of packages to build
Needed in https://github.com/sPHENIX-Collaboration/coresoftware/pull/1990
=> add new globalvertex package

utils/rebuild/packages.txt
Needed for the new stepping action
=> move g4hcals after CaloBase

utils/rebuild/packages.txt
Move also g4detectors for the old hcals
=> move g4detectors after CaloBase

utils/rebuild/packages.txt
Evgeny modified and moved this code to the tpc dir
=> comment out coresoftware/offline/packages/rawtodst

utils/rebuild/build.pl
This PR adds the option to set the cc mail recipient
=> add option for manager email

utils/rebuild/packages.txt
Add jetbase package to the compilation (so jenkins runs it)
=> Add coresoftware/offline/packages/jetbase|0ds.johnny@gmail.com

utils/rebuild/packages.txt
This PR rearranges the build order for the bbc
=> bbc need libcalo_io

utils/rebuild/packages.txt
=> add coresoftware/offline/framework/fun4allutils|pinkenburg@bnl.gov

utils/rebuild/packages.txt
This PR adds the package for the streaming readout hit objects starting with the intt
=> Add coresoftware/offline/framework/ffarawobjects|pinkenburg@bnl.gov

utils/rebuild/packages.txt
This PR adds Ejiros eventplaneinfo package to the build so jenkins will see it
=> add coresoftware/offline/packages/eventplaneinfo

utils/rebuild/packages.txt
Needs to coordinate with https://github.com/sPHENIX-Collaboration/coresoftware/pull/2309
=> Update package name and order

utils/rebuild/packages.txt
Reverts sPHENIX-Collaboration/utilities#319
Reverting so as to not break the nightly build now that the Jenkins test is running...
=> Revert "Update package name and order"

utils/rebuild/packages.txt
Reverts sPHENIX-Collaboration/utilities#321, Joe does this already in his PR
=> Revert "add mbd to be able to rename bbc -> mbd"

utils/rebuild/packages.txt
remove duplicate eventplaneinfo before epd
=> move eventplaneinfo after mbd and epd

utils/rebuild/packages.txt
=> remove eventplane from packages

utils/rebuild/build.pl
This PR installs the rebuild.info which contains the git hashes before cvmfs is released, so it shows up in cvmfs
=> install rebuild.info before the cvmfs release

utils/rebuild/packages.txt
This PR adds coresoftware/validation/CaloValid to the build packages
=> add coresoftware/validation/CaloValid|bs3402@columbia.edu

utils/rebuild/build.pl
the last PR resulted in a perl warning - this PR fixes that
=> fix single use DBI::error warning

utils/rebuild/packages.txt
=> add new event display package

utils/rebuild/packages.txt
The trigger package needs to be moved after CaloReco
=> move coresoftware/offline/packages/trigger after CaloReco

utils/rebuild/packages.txt
=> add comment about libtrigger order

utils/rebuild/packages.txt
Adding packages which wasn't build so far
=> add fillDigitalCurrentMaps

utils/rebuild/packages.txt
This PR adds offline/database/rundb to our packages
=> add coresoftware/offline/database/rundb

utils/rebuild/packages.txt
=> add xingshift and localpol

utils/rebuild/packages.txt
Add new calo validation area, will remove old one after changes go through
=> feat: add new calo valid location

utils/rebuild/packages.txt
=> add new trigger qa package

utils/rebuild/packages.txt
=> feat: add tpc qa

jenkins/built-test/full-build.extra_packages.txt
adds new calo ana package from tutorials into jenkins build, at the request of Anthony
=> feat: add new calo ana

utils/rebuild/packages.txt
This PR removes packages which are missing in our repo and are therefore not being build
=> remove missing packages

utils/rebuild/packages.txt
This PR adds QA/Global to our build
=> add coresoftware/offline/QA/Global

utils/rebuild/packages.txt
=> feat: kfp qa package

utils/rebuild/packages.txt
Adds new caloqa package to build for jenkins testing
=> add new caloqa

utils/rebuild/packages.txt
=> add jet skimmer

utils/rebuild/packages.txt
package list needed a reshuffle for a new dependency
=> centrality package needs trigger

utils/rebuild/build.pl
This adds the insure build to alma9
=> Alma9 insure

utils/rebuild/packages.txt
Adds bco counting package to the list
=> new bco package

utils/rebuild/packages.txt
=> remove commented out pg, phpythia6

jenkins/built-test/test-tracking-reconstruction-prdf.Jenkinsfile
Adds a jenkins file for running the prdf reconstruction pipeline. Same as the default but attempts to archive the output QA root file
=> feat: prdf reco jenkins file

jenkins/built-test/Build-Master.Jenkinsfile
Adds the tracking prdf reco pipeline to the master jenkins build
=> feat: add tracking prdf reco to master build

utils/rebuild/packages.txt
=> build HepMCTrigger

utils/rebuild/packages.txt
This PR adds the line laser package to the build
=> add coresoftware/offline/packages/TpcLineLaserDiode
